title: Image Retreival System
description: Deep Hashing Based Image Retreival, retrieve images in the database with similarity
about:


  This is a Image Retreival System baseed on Deep Hashing built on top of Pytorch.


  The project was build by []()
  and []().


  More info and the source code can he found below.


  - [Blog]()

  - [Web app]()

  - [Video]()


code:

sampleImages:
  - name: frog
    url: https://dadsh-cifar10.oss-cn-shenzhen-internal.aliyuncs.com/images/1.jpg
  - name: dog
    url: https://dadsh-cifar10.oss-cn-shenzhen-internal.aliyuncs.com/images/10000.jpg
  - name: ship
    url: https://dadsh-cifar10.oss-cn-shenzhen-internal.aliyuncs.com/images/20001.jpg
  - name: truck
    url: https://dadsh-cifar10.oss-cn-shenzhen-internal.aliyuncs.com/images/2.jpg
  - name: deer
    url: https://dadsh-cifar10.oss-cn-shenzhen-internal.aliyuncs.com/images/4000.jpg
